openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8001
  description: Generated server url
tags:
- name: Order Service API
  description: Сервис Заказов
paths:
  /api/v1/orders:
    get:
      tags:
      - Order Service API
      summary: Получить список всех заказов
      operationId: getOrders
      responses:
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
        "200":
          description: Список заказов получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderResponse"
    put:
      tags:
      - Order Service API
      summary: Обновить заказ
      operationId: updateOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderRequest"
        required: true
      responses:
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
        "200":
          description: Заказ успешно обновлен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
        "400":
          description: Переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
        "404":
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
    post:
      tags:
      - Order Service API
      summary: Создать заказ
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
        required: true
      responses:
        "200":
          description: Новый заказ успешно создан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
        "400":
          description: Переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
  /api/v1/orders/{order_id}:
    get:
      tags:
      - Order Service API
      summary: Получить заказ по идентификатору
      operationId: getOrder
      parameters:
      - name: order_id
        in: path
        description: Идентификатор заказа
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Информация о заказе получена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
        "404":
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
    delete:
      tags:
      - Order Service API
      summary: Удалить заказ
      operationId: deleteOrder
      parameters:
      - name: order_id
        in: path
        description: Идентификатор заказа
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "500":
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
        "200":
          description: Заказ успешно удален
        "404":
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderErrorResponse"
components:
  schemas:
    DeliveryAddressRequest:
      required:
      - apartment
      - city
      - houseNumber
      - postcode
      - region
      - street
      type: object
      properties:
        region:
          type: string
          description: Наименование территориального региона доставки
        city:
          type: string
          description: Наименование города
        street:
          type: string
          description: Наименование улицы
        houseNumber:
          type: integer
          description: Номер дома
          format: int32
        apartment:
          type: integer
          description: Номер квартиры
          format: int32
          nullable: true
        postcode:
          type: integer
          description: Почтовый индекс
          format: int32
      description: Адрес доставки заказа
    OrderItemRequest:
      required:
      - cost
      - count
      - name
      type: object
      properties:
        name:
          type: string
          description: Наименование элемента заказа
        count:
          type: integer
          description: Количество элементов в заказе
          format: int32
        cost:
          type: number
          description: Стоимость элемента заказа
      description: Элемент из заказа
    OrderStatusEnum:
      type: string
      description: Состояние заказа
      example: CREATED
      enum:
      - CREATED
      - CANCELED
      - PROCESSED
      - COLLECTED
      - DELIVERED
      - COMPLETED
    UpdateOrderRequest:
      required:
      - address
      - cost
      - id
      - items
      - status
      - uid
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор операции
          format: int64
        uid:
          type: string
          description: Присвоенный идентификатор заказа
        status:
          $ref: "#/components/schemas/OrderStatusEnum"
        cost:
          type: number
          description: Стоимость всего заказа
        items:
          type: array
          description: "Список элементов, входящих в заказ"
          items:
            $ref: "#/components/schemas/OrderItemRequest"
        address:
          $ref: "#/components/schemas/DeliveryAddressRequest"
      description: Запрос на обновление текущей операции
    OrderErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Описание ошибки
          example: Заказ не найден
        description:
          type: string
          description: Пояснения о причинах ошибки
    DeliveryAddressResponse:
      required:
      - apartment
      - city
      - houseNumber
      - id
      - postcode
      - region
      - street
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор адреса доставки
          format: int64
        region:
          type: string
          description: Наименование территориального региона доставки
        city:
          type: string
          description: Наименование города
        street:
          type: string
          description: Наименование улицы
        houseNumber:
          type: integer
          description: Номер дома
          format: int32
        apartment:
          type: integer
          description: Номер квартиры
          format: int32
          nullable: true
        postcode:
          type: integer
          description: Почтовый индекс
          format: int32
      description: Адрес доставки заказа
    OrderItemResponse:
      required:
      - cost
      - count
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор элемента заказа
          format: int64
        name:
          type: string
          description: Наименование элемента заказа
        count:
          type: integer
          description: Количество элементов в заказе
          format: int32
        cost:
          type: number
          description: Стоимость элемента заказа
      description: Элемент из заказа
    OrderResponse:
      required:
      - address
      - cost
      - id
      - items
      - status
      - uid
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор заказа
          format: int64
        uid:
          type: string
          description: Присвоенный идентификатор заказа
        status:
          $ref: "#/components/schemas/OrderStatusEnum"
        cost:
          type: number
          description: Стоимость всего заказа
        items:
          type: array
          description: "Список элементов, входящих в заказ"
          items:
            $ref: "#/components/schemas/OrderItemResponse"
        address:
          $ref: "#/components/schemas/DeliveryAddressResponse"
      description: Текущий заказ
    CreateOrderRequest:
      required:
      - address
      - cost
      - items
      type: object
      properties:
        cost:
          type: number
          description: Стоимость всего заказа
        items:
          type: array
          description: "Список элементов, входящих в заказ"
          items:
            $ref: "#/components/schemas/OrderItemRequest"
        address:
          $ref: "#/components/schemas/DeliveryAddressRequest"
      description: Запрос на создание нового заказа
