server:
  port: 8002
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:testpaymentdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springframework:
        cloud:
          stream:
            messaging: trace
  file:
    name: logs/order-service.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM, aux}/order-service.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      total-size-cap: 100MB
      max-history: 10