server:
  port: 8001
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    function:
      definition: orderProducePayment;paymentConsume;orderProduceShipment;shipmentConsume
    stream:
      bindings:
        orderProducePayment-out-0:
          destination: create-payment-topic
        paymentConsume-in-0:
          destination: payment-response-topic
          group: payment-group
          consumer:
            autoCommitOffset: true
        orderProduceShipment-out-0:
          destination: create-shipment-topic
        shipmentConsume-in-0:
          destination: shipment-response-topic
          group: shipment-group
          consumer:
            autoCommitOffset: true
      kafka:
        binder:
          brokers: localhost:9093

logging:
  level:
    org:
      springframework:
        cloud:
          stream:
            messaging: trace
  file:
    name: logs/order-service.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM, aux}/order-service.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      total-size-cap: 100MB
      max-history: 10

resilience4j:
  retry:
    instances:
      paymentServiceRetry:
        maxAttempts: 3                 # Максимальное число попыток выполнения метода (включая первую)
        waitDuration: 500ms            # Время ожидания между попытками
        retryExceptions:
          - feign.FeignException       # Исключения, при которых происходит повторная попытка
        ignoreExceptions:
          - java.lang.RuntimeException # Исключения, игнорируемые для повторных попыток

  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        registerHealthIndicator: true     # Включить мониторинг состояния цепи
        slidingWindowSize: 50             # Размер окна для оценки ошибок (сколько вызовов учитывается)
        slidingWindowType: COUNT_BASED    # смотрит на последние 50 вызово
        failureRateThreshold: 50          # Процент ошибок, при котором цепь откроется
        waitDurationInOpenState: 30s      # Время, в течение которого цепь останется открытой
        permittedNumberOfCallsInHalfOpenState: 10 # Количество вызовов в полузакрытом состоянии для проверки
        minimumNumberOfCalls: 20          # Минимальное число вызовов для оценки состояния цепи
        automaticTransitionFromOpenToHalfOpenEnabled: true # автоматом перейдёт в HALF_OPEN
        recordExceptions:
          - feign.FeignException          # Исключения, которые считаются ошибками
        ignoreExceptions:
          - java.lang.RuntimeException    # Исключения, которые игнорируются при оценке ошибок

      orderServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - feign.FeignException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - com.mihenze.mscurse.orderservice.exception.NotFoundOrderException

  bulkhead:
    instances:
      paymentServiceBulkhead:
        maxConcurrentCalls: 5  # Максимальное число параллельных вызовов, разрешенных одновременно
        maxWaitDuration: 0s    # Время ожидания, если все слоты заняты; 0 — отказ сразу, без ожидания

  ratelimiter:
    instances:
      paymentServiceRateLimiter:
        limitForPeriod: 10      # Максимальное количество вызовов за один период (например, за 1 секунду)
        limitRefreshPeriod: 1s  # Период, за который сбрасывается счетчик лимитов (например, 1 секунда)
        timeoutDuration: 0s     # Время ожидания, если лимит достигнут; 0 означает сразу отказ, без ожидания

integration:
  payment-service:
    base-url: http://localhost:8002/api/v1/payments

app:
  bindings:
    payment-created: orderProducePayment-out-0
    shipment-created: orderProduceShipment-out-0
    payment-confirm: paymentConsume-in-0
    shipment-confirm: shipmentConsume-in-0